security:
    firewalls:
        beauty_webservice:
            pattern: ^/webservice
            stateless: true
            provider: pimcore_admin
            guard:
                authenticators:
                    - AppBundle\Security\Guard\WebserviceAuthenticator